name: Docker Build and Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -t ghcr.io/quiltmc/javadoc-publish:latest -t ghcr.io/quiltmc/javadoc-publish:${GITHUB_SHA} .
      - run: docker push ghcr.io/quiltmc/javadoc-publish:latest
      - run: docker push ghcr.io/quiltmc/javadoc-publish:${GITHUB_SHA}
